export const ROADSIDE_ASSISTANCE = 'ROADSIDE ASSISTANCE';
export const PARTNERS = 'PARTNERS';
export const PREVIOUS = 'PREVIOUS';
export const NEXT = 'NEXT';
export const DEALER_SIGNUP_FORM_HEADER = 'ENTER YOUR DETAILS BELOW';
export const DEALER_SIGNUP_MODAL_HEADER = 'PARTNER WITH US';
